<?php
namespace Bonecrusher\Hexon\Api;

use Bonecrusher\Hexon\Hexon;
use Bonecrusher\Hexon\Support\Traits\{GetRequests, GlobalRequests};

class Sites extends Hexon
{
    use GetRequests, GlobalRequests;

    public $code = 'Code';
    public $name = 'Localized name of the site.';
    public $url = 'URL';
    public $short_description = 'Short description';
    public $long_description = 'Long description';
    public $signup_url = 'Website where dealers can sign up for a subscription';
    public $info_url = 'Website where dealers can find more information';
    public $logo = 'The BASE64 encoded logo string belonging to this site. This field is not returned by default due to the size of the field. Base64 decode the string to receive the binary image data.';
    public $leads = 'The ability to receive leads generated by the site in Doorlinken Voorraad';
    public $status = 'The current status of the interface between Hexon and the site.';
    public $vehicle_categories = 'The vehiclecategory that can be advertised on this site';
}
